/**
 * GENERATED by portal/scripts/gen-guidance.mjs from data/guidance/*.yaml.
 * Do not edit by hand — run `pnpm gen:guidance` after changing a manifest.
 */
import type { Guidance } from "./guidance";

export const GUIDANCES: ReadonlyArray<Guidance> = [
  {
    id: "new-app-onboarding",
    title: "New Application Onboarding",
    type: "route",
    scenario: "onboarding",
    family: "onboard",
    objective: "Help an application team onboard a new cloud workload to the standard platform.",
    destination: {
      title: "Application ready for standard cloud deployment",
      description: "The app has approved access, a provisioning path, and passes readiness checks.",
    },
    owner: {
      team: "Cloud Platform",
      support: "cloud-platform-support",
    },
    status: "published",
    version: "1.2.0",
    lastReviewed: "2026-04-18",
    appliesTo: {
      services: ["serverless-compute"],
      landingZones: ["central-landing-zone"],
    },
    sources: ["platform-reference-guide", "central-lz-confluence"],
    steps: [
      {
        id: "choose-landing-zone",
        title: "Choose landing zone",
        kind: "decision",
        description:
          "Select the landing zone that matches this workload's data and compliance needs.",
        why: "The landing zone sets the guardrails, networking, and IAM boundary your app inherits.",
        tasks: [
          {
            id: "review-options",
            title: "Review landing zone options",
            action: {
              type: "atlas_page",
              label: "Open landing zones",
              target: "/catalog",
            },
          },
          {
            id: "confirm-choice",
            title: "Confirm the selected landing zone",
            required: true,
          },
        ],
        sources: ["central-lz-confluence"],
      },
      {
        id: "request-access",
        title: "Request access",
        kind: "action",
        description: "Open the approved access request path for the selected landing zone.",
        why: "Access must be granted through the approved request flow — Atlas does not submit it for you.",
        tasks: [
          {
            id: "open-request-form",
            title: "Open the access request form",
            required: true,
            action: {
              type: "external_link",
              label: "Open request form",
              target: "https://example.internal/access-request",
            },
          },
        ],
      },
      {
        id: "open-tfe",
        title: "Open Terraform Enterprise",
        kind: "action",
        description: "Use the approved TFE workspace or module to provision infrastructure.",
        why: "Provisioning runs through the approved infrastructure-as-code path, not the console.",
        tasks: [
          {
            id: "open-tfe-workspace",
            title: "Open the standard TFE workspace",
            required: true,
            action: {
              type: "tool_link",
              label: "Open TFE workspace",
              target: "https://example.internal/tfe/standard",
            },
          },
          {
            id: "copy-module",
            title: "Copy the module reference",
            action: {
              type: "copy_text",
              label: "Copy module ref",
              text: 'module "app" { source = "app.terraform.io/example/standard/aws" }',
            },
          },
        ],
        sources: ["lambda-module-readme"],
      },
      {
        id: "connect-harness",
        title: "Connect Harness pipeline",
        kind: "action",
        description: "Connect the standard deployment path for your service.",
        why: "Deployments are promoted through the approved Harness pipeline templates.",
        tasks: [
          {
            id: "open-harness",
            title: "Open the Harness setup guide",
            action: {
              type: "external_link",
              label: "Open Harness guide",
              target: "https://example.internal/harness/standard",
            },
          },
        ],
      },
      {
        id: "production-readiness",
        title: "Production readiness",
        kind: "checklist",
        description: "Confirm required checks before promoting the workload to production.",
        why: "Readiness is verified outside Atlas — this is the checklist, not a sign-off record.",
        tasks: [
          {
            id: "logging",
            title: "Logging and monitoring enabled",
            required: true,
          },
          {
            id: "tags",
            title: "Required resource tags applied",
            required: true,
          },
          {
            id: "iam",
            title: "IAM role pattern reviewed",
            required: true,
          },
          {
            id: "support-owner",
            title: "Support owner confirmed",
            required: true,
          },
        ],
        sources: ["logging-standard-doc", "iam-boundary-policy"],
      },
      {
        id: "done",
        title: "Onboarding complete",
        kind: "destination",
        description: "The application is ready for standard cloud deployment.",
      },
    ],
  },
  {
    id: "api-gateway-adoption",
    title: "Adopt API Gateway",
    type: "route",
    scenario: "service_enablement",
    family: "enable",
    objective:
      "Help an application team put API Gateway in front of their workload using the approved module.",
    destination: {
      title: "API Gateway fronting the application",
      description:
        "The app routes through a module-provisioned API Gateway with a private backend.",
    },
    owner: {
      team: "Cloud Platform",
      support: "cloud-platform-support",
    },
    status: "published",
    version: "1.0.0",
    lastReviewed: "2026-05-02",
    appliesTo: {
      services: ["api-gateway"],
      landingZones: ["central-landing-zone"],
    },
    sources: ["apigateway-module-readme", "apigateway-integration-guide"],
    steps: [
      {
        id: "understand-fit",
        title: "Understand how it fits",
        kind: "action",
        description: "Review where API Gateway sits in your architecture before provisioning.",
        why: "API Gateway is your public edge — it fronts Lambda or a private VPC-link backend.",
        tasks: [
          {
            id: "open-datasheet",
            title: "Open the API Gateway datasheet",
            action: {
              type: "atlas_page",
              label: "Open API Gateway",
              target: "/catalog/api-gateway",
            },
          },
          {
            id: "review-integration",
            title: "Review the integration guide",
            action: {
              type: "external_link",
              label: "View integration guide",
              target: "https://confluence.example.com/display/CLOUD/API+Gateway+Integration",
            },
          },
        ],
        sources: ["apigateway-integration-guide"],
      },
      {
        id: "get-terraform",
        title: "Get the Terraform starter",
        kind: "action",
        description: "Use the approved module — copy the starter and pin it in your workspace.",
        why: "Provisioning runs through the approved module, not the console.",
        tasks: [
          {
            id: "open-module",
            title: "Open the API Gateway module",
            required: true,
            action: {
              type: "tool_link",
              label: "Open module",
              target: "https://github.com/example/terraform-aws-apigateway",
            },
          },
          {
            id: "copy-starter",
            title: "Copy the Terraform starter",
            action: {
              type: "copy_text",
              label: "Copy starter",
              text: 'module "api" {\n  source     = "app.terraform.io/example/apigateway/aws"\n  name       = "orders-api"\n  protocol   = "HTTP"\n  stage_name = "prod"\n  routes = {\n    "POST /orders"     = { lambda_arn = module.orders_fn.arn }\n    "GET /orders/{id}" = { lambda_arn = module.orders_fn.arn }\n  }\n}',
            },
          },
        ],
        sources: ["apigateway-module-readme"],
      },
      {
        id: "wire-backend",
        title: "Wire your backend",
        kind: "action",
        description: "Point each route at your application function and keep the backend private.",
        why: "The module creates the integration and invoke permission from the route's lambda_arn.",
        tasks: [
          {
            id: "set-routes",
            title: "Map routes to your Lambda ARNs",
            required: true,
          },
          {
            id: "private-backend",
            title: "Confirm the backend stays private (no public endpoint)",
            required: true,
          },
        ],
        sources: ["apigateway-module-readme"],
      },
      {
        id: "validate",
        title: "Validate before production",
        kind: "checklist",
        description: "Confirm edge controls before promoting the API.",
        why: "The gateway is the public entry point — throttling and logging are required.",
        tasks: [
          {
            id: "throttling",
            title: "Request throttling configured",
            required: true,
          },
          {
            id: "access-logs",
            title: "Access logging enabled",
            required: true,
          },
          {
            id: "authz",
            title: "Authorizer attached to protected routes",
            required: true,
          },
        ],
        sources: ["apigateway-integration-guide"],
      },
      {
        id: "done",
        title: "API Gateway adopted",
        kind: "destination",
        description: "The application is fronted by a module-provisioned API Gateway.",
      },
    ],
  },
  {
    id: "s3-adoption",
    title: "Adopt Amazon S3",
    type: "route",
    scenario: "service_enablement",
    family: "enable",
    objective:
      "Help an application team provision an approved, guarded S3 bucket for its workload.",
    destination: {
      title: "Application backed by a guarded S3 bucket",
      description:
        "The app stores data in a module-provisioned bucket with encryption and no public access.",
    },
    owner: {
      team: "Cloud Platform",
      support: "cloud-platform-support",
    },
    status: "published",
    version: "1.0.0",
    lastReviewed: "2026-05-02",
    appliesTo: {
      services: ["aws-s3"],
      landingZones: ["central-landing-zone"],
    },
    sources: ["s3-module-readme", "s3-policy-doc"],
    steps: [
      {
        id: "understand-fit",
        title: "Understand how it fits",
        kind: "action",
        description: "Review the storage guardrails your bucket must satisfy.",
        why: "Buckets inherit the platform's public-access and encryption policy — design for it up front.",
        tasks: [
          {
            id: "open-datasheet",
            title: "Open the Amazon S3 datasheet",
            action: {
              type: "atlas_page",
              label: "Open Amazon S3",
              target: "/catalog/aws-s3",
            },
          },
          {
            id: "review-user-guide",
            title: "Review the S3 user guide",
            action: {
              type: "external_link",
              label: "View user guide",
              target: "https://confluence.example.com/display/CLOUD/S3+User+Guide",
            },
          },
        ],
        sources: ["s3-policy-doc"],
      },
      {
        id: "get-terraform",
        title: "Get the Terraform starter",
        kind: "action",
        description: "Use the approved module — copy the starter and pin it in your workspace.",
        why: "Provisioning runs through the approved module, not the console.",
        tasks: [
          {
            id: "open-module",
            title: "Open the S3 module",
            required: true,
            action: {
              type: "tool_link",
              label: "Open module",
              target: "https://github.com/example/terraform-aws-s3",
            },
          },
          {
            id: "copy-starter",
            title: "Copy the Terraform starter",
            action: {
              type: "copy_text",
              label: "Copy starter",
              text: 'module "bucket" {\n  source              = "app.terraform.io/example/s3/aws"\n  name                = "orders-assets"\n  versioning          = true\n  block_public_access = true\n  encryption          = "aws:kms"\n}',
            },
          },
        ],
        sources: ["s3-module-readme"],
      },
      {
        id: "validate",
        title: "Validate before production",
        kind: "checklist",
        description: "Confirm the bucket meets storage guardrails.",
        why: "Public exposure of buckets is a hard production blocker.",
        tasks: [
          {
            id: "no-public",
            title: "Block-public-access enabled",
            required: true,
          },
          {
            id: "encryption",
            title: "Default encryption (KMS) enabled",
            required: true,
          },
          {
            id: "versioning",
            title: "Versioning enabled for recoverability",
            required: true,
          },
        ],
        sources: ["s3-policy-doc"],
      },
      {
        id: "done",
        title: "Amazon S3 adopted",
        kind: "destination",
        description: "The application stores data in a guarded, module-provisioned bucket.",
      },
    ],
  },
  {
    id: "textract-adoption",
    title: "Adopt AWS Textract",
    type: "route",
    scenario: "service_enablement",
    family: "enable",
    objective:
      "Help an application team call Textract from a private subnet using the approved module.",
    destination: {
      title: "Application calling Textract privately",
      description: "The app reaches Textract through a module-provisioned private endpoint.",
    },
    owner: {
      team: "Cloud Platform",
      support: "cloud-platform-support",
    },
    status: "published",
    version: "1.0.0",
    lastReviewed: "2026-05-02",
    appliesTo: {
      services: ["aws-textract"],
      landingZones: ["central-landing-zone"],
    },
    sources: ["textract-module-readme"],
    steps: [
      {
        id: "understand-fit",
        title: "Understand how it fits",
        kind: "action",
        description: "Review how Textract is reached from a private subnet.",
        why: "Document workloads reach Textract through a private interface endpoint, not the public internet.",
        tasks: [
          {
            id: "open-datasheet",
            title: "Open the AWS Textract datasheet",
            action: {
              type: "atlas_page",
              label: "Open AWS Textract",
              target: "/catalog/aws-textract",
            },
          },
          {
            id: "review-user-guide",
            title: "Review the Textract user guide",
            action: {
              type: "external_link",
              label: "View user guide",
              target: "https://confluence.example.com/display/CLOUD/Textract+User+Guide",
            },
          },
        ],
        sources: ["textract-module-readme"],
      },
      {
        id: "get-terraform",
        title: "Get the Terraform starter",
        kind: "action",
        description: "Use the approved module — copy the starter and pin it in your workspace.",
        why: "Provisioning runs through the approved module, not the console.",
        tasks: [
          {
            id: "open-module",
            title: "Open the Textract module",
            required: true,
            action: {
              type: "tool_link",
              label: "Open module",
              target: "https://github.com/example/terraform-aws-textract",
            },
          },
          {
            id: "copy-starter",
            title: "Copy the Terraform starter",
            action: {
              type: "copy_text",
              label: "Copy starter",
              text: 'module "textract" {\n  source             = "app.terraform.io/example/textract/aws"\n  name               = "doc-ocr"\n  endpoint_type      = "interface"\n  private_subnet_ids = var.private_subnet_ids\n}',
            },
          },
        ],
        sources: ["textract-module-readme"],
      },
      {
        id: "validate",
        title: "Validate before production",
        kind: "checklist",
        description: "Confirm private connectivity before promoting.",
        why: "Textract access must stay on the private path.",
        tasks: [
          {
            id: "private-endpoint",
            title: "Interface endpoint reachable from the subnet",
            required: true,
          },
          {
            id: "no-public",
            title: "No public egress path required",
            required: true,
          },
        ],
        sources: ["textract-module-readme"],
      },
      {
        id: "done",
        title: "AWS Textract adopted",
        kind: "destination",
        description: "The application calls Textract through a private endpoint.",
      },
    ],
  },
];
