/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as RegionsRouteImport } from './routes/regions'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as GuidanceRouteImport } from './routes/guidance'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as AvailabilityRouteImport } from './routes/availability'
import { Route as AskRouteImport } from './routes/ask'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SourcesIndexRouteImport } from './routes/sources.index'
import { Route as SkillsIndexRouteImport } from './routes/skills.index'
import { Route as GuidanceIndexRouteImport } from './routes/guidance.index'
import { Route as CatalogIndexRouteImport } from './routes/catalog.index'
import { Route as AvailabilityIndexRouteImport } from './routes/availability.index'
import { Route as SourcesSourceIdRouteImport } from './routes/sources.$sourceId'
import { Route as ProtoWhatsnewRouteImport } from './routes/proto.whatsnew'
import { Route as ProtoSourcesRouteImport } from './routes/proto.sources'
import { Route as ProtoSkillsRouteImport } from './routes/proto.skills'
import { Route as ProtoOverviewRouteImport } from './routes/proto.overview'
import { Route as ProtoHomeRouteImport } from './routes/proto.home'
import { Route as ProtoGuidanceRouteImport } from './routes/proto.guidance'
import { Route as ProtoCatalogRouteImport } from './routes/proto.catalog'
import { Route as ProtoCapabilityRouteImport } from './routes/proto.capability'
import { Route as ProtoAskRouteImport } from './routes/proto.ask'
import { Route as GuidanceGuidanceIdRouteImport } from './routes/guidance.$guidanceId'
import { Route as GuardrailsGuardrailIdRouteImport } from './routes/guardrails.$guardrailId'
import { Route as CatalogTopicIdRouteImport } from './routes/catalog.$topicId'
import { Route as ProtoSourcesSourceIdRouteImport } from './routes/proto.sources_.$sourceId'
import { Route as ProtoGuidanceGuidanceIdRouteImport } from './routes/proto.guidance_.$guidanceId'

const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionsRoute = RegionsRouteImport.update({
  id: '/regions',
  path: '/regions',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidanceRoute = GuidanceRouteImport.update({
  id: '/guidance',
  path: '/guidance',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AvailabilityRoute = AvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesIndexRoute = SourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SourcesRoute,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidanceIndexRoute = GuidanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuidanceRoute,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CatalogRoute,
} as any)
const AvailabilityIndexRoute = AvailabilityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AvailabilityRoute,
} as any)
const SourcesSourceIdRoute = SourcesSourceIdRouteImport.update({
  id: '/$sourceId',
  path: '/$sourceId',
  getParentRoute: () => SourcesRoute,
} as any)
const ProtoWhatsnewRoute = ProtoWhatsnewRouteImport.update({
  id: '/proto/whatsnew',
  path: '/proto/whatsnew',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoSourcesRoute = ProtoSourcesRouteImport.update({
  id: '/proto/sources',
  path: '/proto/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoSkillsRoute = ProtoSkillsRouteImport.update({
  id: '/proto/skills',
  path: '/proto/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoOverviewRoute = ProtoOverviewRouteImport.update({
  id: '/proto/overview',
  path: '/proto/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoHomeRoute = ProtoHomeRouteImport.update({
  id: '/proto/home',
  path: '/proto/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoGuidanceRoute = ProtoGuidanceRouteImport.update({
  id: '/proto/guidance',
  path: '/proto/guidance',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoCatalogRoute = ProtoCatalogRouteImport.update({
  id: '/proto/catalog',
  path: '/proto/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoCapabilityRoute = ProtoCapabilityRouteImport.update({
  id: '/proto/capability',
  path: '/proto/capability',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoAskRoute = ProtoAskRouteImport.update({
  id: '/proto/ask',
  path: '/proto/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidanceGuidanceIdRoute = GuidanceGuidanceIdRouteImport.update({
  id: '/$guidanceId',
  path: '/$guidanceId',
  getParentRoute: () => GuidanceRoute,
} as any)
const GuardrailsGuardrailIdRoute = GuardrailsGuardrailIdRouteImport.update({
  id: '/guardrails/$guardrailId',
  path: '/guardrails/$guardrailId',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogTopicIdRoute = CatalogTopicIdRouteImport.update({
  id: '/$topicId',
  path: '/$topicId',
  getParentRoute: () => CatalogRoute,
} as any)
const ProtoSourcesSourceIdRoute = ProtoSourcesSourceIdRouteImport.update({
  id: '/proto/sources_/$sourceId',
  path: '/proto/sources/$sourceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoGuidanceGuidanceIdRoute = ProtoGuidanceGuidanceIdRouteImport.update({
  id: '/proto/guidance_/$guidanceId',
  path: '/proto/guidance/$guidanceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/availability': typeof AvailabilityRouteWithChildren
  '/catalog': typeof CatalogRouteWithChildren
  '/guidance': typeof GuidanceRouteWithChildren
  '/overview': typeof OverviewRoute
  '/regions': typeof RegionsRoute
  '/sources': typeof SourcesRouteWithChildren
  '/catalog/$topicId': typeof CatalogTopicIdRoute
  '/guardrails/$guardrailId': typeof GuardrailsGuardrailIdRoute
  '/guidance/$guidanceId': typeof GuidanceGuidanceIdRoute
  '/proto/ask': typeof ProtoAskRoute
  '/proto/capability': typeof ProtoCapabilityRoute
  '/proto/catalog': typeof ProtoCatalogRoute
  '/proto/guidance': typeof ProtoGuidanceRoute
  '/proto/home': typeof ProtoHomeRoute
  '/proto/overview': typeof ProtoOverviewRoute
  '/proto/skills': typeof ProtoSkillsRoute
  '/proto/sources': typeof ProtoSourcesRoute
  '/proto/whatsnew': typeof ProtoWhatsnewRoute
  '/sources/$sourceId': typeof SourcesSourceIdRoute
  '/availability/': typeof AvailabilityIndexRoute
  '/catalog/': typeof CatalogIndexRoute
  '/guidance/': typeof GuidanceIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/sources/': typeof SourcesIndexRoute
  '/proto/guidance/$guidanceId': typeof ProtoGuidanceGuidanceIdRoute
  '/proto/sources/$sourceId': typeof ProtoSourcesSourceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/overview': typeof OverviewRoute
  '/regions': typeof RegionsRoute
  '/catalog/$topicId': typeof CatalogTopicIdRoute
  '/guardrails/$guardrailId': typeof GuardrailsGuardrailIdRoute
  '/guidance/$guidanceId': typeof GuidanceGuidanceIdRoute
  '/proto/ask': typeof ProtoAskRoute
  '/proto/capability': typeof ProtoCapabilityRoute
  '/proto/catalog': typeof ProtoCatalogRoute
  '/proto/guidance': typeof ProtoGuidanceRoute
  '/proto/home': typeof ProtoHomeRoute
  '/proto/overview': typeof ProtoOverviewRoute
  '/proto/skills': typeof ProtoSkillsRoute
  '/proto/sources': typeof ProtoSourcesRoute
  '/proto/whatsnew': typeof ProtoWhatsnewRoute
  '/sources/$sourceId': typeof SourcesSourceIdRoute
  '/availability': typeof AvailabilityIndexRoute
  '/catalog': typeof CatalogIndexRoute
  '/guidance': typeof GuidanceIndexRoute
  '/skills': typeof SkillsIndexRoute
  '/sources': typeof SourcesIndexRoute
  '/proto/guidance/$guidanceId': typeof ProtoGuidanceGuidanceIdRoute
  '/proto/sources/$sourceId': typeof ProtoSourcesSourceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/availability': typeof AvailabilityRouteWithChildren
  '/catalog': typeof CatalogRouteWithChildren
  '/guidance': typeof GuidanceRouteWithChildren
  '/overview': typeof OverviewRoute
  '/regions': typeof RegionsRoute
  '/sources': typeof SourcesRouteWithChildren
  '/catalog/$topicId': typeof CatalogTopicIdRoute
  '/guardrails/$guardrailId': typeof GuardrailsGuardrailIdRoute
  '/guidance/$guidanceId': typeof GuidanceGuidanceIdRoute
  '/proto/ask': typeof ProtoAskRoute
  '/proto/capability': typeof ProtoCapabilityRoute
  '/proto/catalog': typeof ProtoCatalogRoute
  '/proto/guidance': typeof ProtoGuidanceRoute
  '/proto/home': typeof ProtoHomeRoute
  '/proto/overview': typeof ProtoOverviewRoute
  '/proto/skills': typeof ProtoSkillsRoute
  '/proto/sources': typeof ProtoSourcesRoute
  '/proto/whatsnew': typeof ProtoWhatsnewRoute
  '/sources/$sourceId': typeof SourcesSourceIdRoute
  '/availability/': typeof AvailabilityIndexRoute
  '/catalog/': typeof CatalogIndexRoute
  '/guidance/': typeof GuidanceIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/sources/': typeof SourcesIndexRoute
  '/proto/guidance_/$guidanceId': typeof ProtoGuidanceGuidanceIdRoute
  '/proto/sources_/$sourceId': typeof ProtoSourcesSourceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask'
    | '/availability'
    | '/catalog'
    | '/guidance'
    | '/overview'
    | '/regions'
    | '/sources'
    | '/catalog/$topicId'
    | '/guardrails/$guardrailId'
    | '/guidance/$guidanceId'
    | '/proto/ask'
    | '/proto/capability'
    | '/proto/catalog'
    | '/proto/guidance'
    | '/proto/home'
    | '/proto/overview'
    | '/proto/skills'
    | '/proto/sources'
    | '/proto/whatsnew'
    | '/sources/$sourceId'
    | '/availability/'
    | '/catalog/'
    | '/guidance/'
    | '/skills/'
    | '/sources/'
    | '/proto/guidance/$guidanceId'
    | '/proto/sources/$sourceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/overview'
    | '/regions'
    | '/catalog/$topicId'
    | '/guardrails/$guardrailId'
    | '/guidance/$guidanceId'
    | '/proto/ask'
    | '/proto/capability'
    | '/proto/catalog'
    | '/proto/guidance'
    | '/proto/home'
    | '/proto/overview'
    | '/proto/skills'
    | '/proto/sources'
    | '/proto/whatsnew'
    | '/sources/$sourceId'
    | '/availability'
    | '/catalog'
    | '/guidance'
    | '/skills'
    | '/sources'
    | '/proto/guidance/$guidanceId'
    | '/proto/sources/$sourceId'
  id:
    | '__root__'
    | '/'
    | '/ask'
    | '/availability'
    | '/catalog'
    | '/guidance'
    | '/overview'
    | '/regions'
    | '/sources'
    | '/catalog/$topicId'
    | '/guardrails/$guardrailId'
    | '/guidance/$guidanceId'
    | '/proto/ask'
    | '/proto/capability'
    | '/proto/catalog'
    | '/proto/guidance'
    | '/proto/home'
    | '/proto/overview'
    | '/proto/skills'
    | '/proto/sources'
    | '/proto/whatsnew'
    | '/sources/$sourceId'
    | '/availability/'
    | '/catalog/'
    | '/guidance/'
    | '/skills/'
    | '/sources/'
    | '/proto/guidance_/$guidanceId'
    | '/proto/sources_/$sourceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskRoute: typeof AskRoute
  AvailabilityRoute: typeof AvailabilityRouteWithChildren
  CatalogRoute: typeof CatalogRouteWithChildren
  GuidanceRoute: typeof GuidanceRouteWithChildren
  OverviewRoute: typeof OverviewRoute
  RegionsRoute: typeof RegionsRoute
  SourcesRoute: typeof SourcesRouteWithChildren
  GuardrailsGuardrailIdRoute: typeof GuardrailsGuardrailIdRoute
  ProtoAskRoute: typeof ProtoAskRoute
  ProtoCapabilityRoute: typeof ProtoCapabilityRoute
  ProtoCatalogRoute: typeof ProtoCatalogRoute
  ProtoGuidanceRoute: typeof ProtoGuidanceRoute
  ProtoHomeRoute: typeof ProtoHomeRoute
  ProtoOverviewRoute: typeof ProtoOverviewRoute
  ProtoSkillsRoute: typeof ProtoSkillsRoute
  ProtoSourcesRoute: typeof ProtoSourcesRoute
  ProtoWhatsnewRoute: typeof ProtoWhatsnewRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
  ProtoGuidanceGuidanceIdRoute: typeof ProtoGuidanceGuidanceIdRoute
  ProtoSourcesSourceIdRoute: typeof ProtoSourcesSourceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regions': {
      id: '/regions'
      path: '/regions'
      fullPath: '/regions'
      preLoaderRoute: typeof RegionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidance': {
      id: '/guidance'
      path: '/guidance'
      fullPath: '/guidance'
      preLoaderRoute: typeof GuidanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/availability': {
      id: '/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/': {
      id: '/sources/'
      path: '/'
      fullPath: '/sources/'
      preLoaderRoute: typeof SourcesIndexRouteImport
      parentRoute: typeof SourcesRoute
    }
    '/skills/': {
      id: '/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidance/': {
      id: '/guidance/'
      path: '/'
      fullPath: '/guidance/'
      preLoaderRoute: typeof GuidanceIndexRouteImport
      parentRoute: typeof GuidanceRoute
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/'
      fullPath: '/catalog/'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/availability/': {
      id: '/availability/'
      path: '/'
      fullPath: '/availability/'
      preLoaderRoute: typeof AvailabilityIndexRouteImport
      parentRoute: typeof AvailabilityRoute
    }
    '/sources/$sourceId': {
      id: '/sources/$sourceId'
      path: '/$sourceId'
      fullPath: '/sources/$sourceId'
      preLoaderRoute: typeof SourcesSourceIdRouteImport
      parentRoute: typeof SourcesRoute
    }
    '/proto/whatsnew': {
      id: '/proto/whatsnew'
      path: '/proto/whatsnew'
      fullPath: '/proto/whatsnew'
      preLoaderRoute: typeof ProtoWhatsnewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/sources': {
      id: '/proto/sources'
      path: '/proto/sources'
      fullPath: '/proto/sources'
      preLoaderRoute: typeof ProtoSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/skills': {
      id: '/proto/skills'
      path: '/proto/skills'
      fullPath: '/proto/skills'
      preLoaderRoute: typeof ProtoSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/overview': {
      id: '/proto/overview'
      path: '/proto/overview'
      fullPath: '/proto/overview'
      preLoaderRoute: typeof ProtoOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/home': {
      id: '/proto/home'
      path: '/proto/home'
      fullPath: '/proto/home'
      preLoaderRoute: typeof ProtoHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/guidance': {
      id: '/proto/guidance'
      path: '/proto/guidance'
      fullPath: '/proto/guidance'
      preLoaderRoute: typeof ProtoGuidanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/catalog': {
      id: '/proto/catalog'
      path: '/proto/catalog'
      fullPath: '/proto/catalog'
      preLoaderRoute: typeof ProtoCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/capability': {
      id: '/proto/capability'
      path: '/proto/capability'
      fullPath: '/proto/capability'
      preLoaderRoute: typeof ProtoCapabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/ask': {
      id: '/proto/ask'
      path: '/proto/ask'
      fullPath: '/proto/ask'
      preLoaderRoute: typeof ProtoAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidance/$guidanceId': {
      id: '/guidance/$guidanceId'
      path: '/$guidanceId'
      fullPath: '/guidance/$guidanceId'
      preLoaderRoute: typeof GuidanceGuidanceIdRouteImport
      parentRoute: typeof GuidanceRoute
    }
    '/guardrails/$guardrailId': {
      id: '/guardrails/$guardrailId'
      path: '/guardrails/$guardrailId'
      fullPath: '/guardrails/$guardrailId'
      preLoaderRoute: typeof GuardrailsGuardrailIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/$topicId': {
      id: '/catalog/$topicId'
      path: '/$topicId'
      fullPath: '/catalog/$topicId'
      preLoaderRoute: typeof CatalogTopicIdRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/proto/sources_/$sourceId': {
      id: '/proto/sources_/$sourceId'
      path: '/proto/sources/$sourceId'
      fullPath: '/proto/sources/$sourceId'
      preLoaderRoute: typeof ProtoSourcesSourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/guidance_/$guidanceId': {
      id: '/proto/guidance_/$guidanceId'
      path: '/proto/guidance/$guidanceId'
      fullPath: '/proto/guidance/$guidanceId'
      preLoaderRoute: typeof ProtoGuidanceGuidanceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AvailabilityRouteChildren {
  AvailabilityIndexRoute: typeof AvailabilityIndexRoute
}

const AvailabilityRouteChildren: AvailabilityRouteChildren = {
  AvailabilityIndexRoute: AvailabilityIndexRoute,
}

const AvailabilityRouteWithChildren = AvailabilityRoute._addFileChildren(
  AvailabilityRouteChildren,
)

interface CatalogRouteChildren {
  CatalogTopicIdRoute: typeof CatalogTopicIdRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
}

const CatalogRouteChildren: CatalogRouteChildren = {
  CatalogTopicIdRoute: CatalogTopicIdRoute,
  CatalogIndexRoute: CatalogIndexRoute,
}

const CatalogRouteWithChildren =
  CatalogRoute._addFileChildren(CatalogRouteChildren)

interface GuidanceRouteChildren {
  GuidanceGuidanceIdRoute: typeof GuidanceGuidanceIdRoute
  GuidanceIndexRoute: typeof GuidanceIndexRoute
}

const GuidanceRouteChildren: GuidanceRouteChildren = {
  GuidanceGuidanceIdRoute: GuidanceGuidanceIdRoute,
  GuidanceIndexRoute: GuidanceIndexRoute,
}

const GuidanceRouteWithChildren = GuidanceRoute._addFileChildren(
  GuidanceRouteChildren,
)

interface SourcesRouteChildren {
  SourcesSourceIdRoute: typeof SourcesSourceIdRoute
  SourcesIndexRoute: typeof SourcesIndexRoute
}

const SourcesRouteChildren: SourcesRouteChildren = {
  SourcesSourceIdRoute: SourcesSourceIdRoute,
  SourcesIndexRoute: SourcesIndexRoute,
}

const SourcesRouteWithChildren =
  SourcesRoute._addFileChildren(SourcesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskRoute: AskRoute,
  AvailabilityRoute: AvailabilityRouteWithChildren,
  CatalogRoute: CatalogRouteWithChildren,
  GuidanceRoute: GuidanceRouteWithChildren,
  OverviewRoute: OverviewRoute,
  RegionsRoute: RegionsRoute,
  SourcesRoute: SourcesRouteWithChildren,
  GuardrailsGuardrailIdRoute: GuardrailsGuardrailIdRoute,
  ProtoAskRoute: ProtoAskRoute,
  ProtoCapabilityRoute: ProtoCapabilityRoute,
  ProtoCatalogRoute: ProtoCatalogRoute,
  ProtoGuidanceRoute: ProtoGuidanceRoute,
  ProtoHomeRoute: ProtoHomeRoute,
  ProtoOverviewRoute: ProtoOverviewRoute,
  ProtoSkillsRoute: ProtoSkillsRoute,
  ProtoSourcesRoute: ProtoSourcesRoute,
  ProtoWhatsnewRoute: ProtoWhatsnewRoute,
  SkillsIndexRoute: SkillsIndexRoute,
  ProtoGuidanceGuidanceIdRoute: ProtoGuidanceGuidanceIdRoute,
  ProtoSourcesSourceIdRoute: ProtoSourcesSourceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
