/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsnewRouteImport } from './routes/whatsnew'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as GuidanceRouteImport } from './routes/guidance'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as AvailabilityRouteImport } from './routes/availability'
import { Route as AskRouteImport } from './routes/ask'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SourcesIndexRouteImport } from './routes/sources.index'
import { Route as SkillsIndexRouteImport } from './routes/skills.index'
import { Route as GuidanceIndexRouteImport } from './routes/guidance.index'
import { Route as CatalogIndexRouteImport } from './routes/catalog.index'
import { Route as AvailabilityIndexRouteImport } from './routes/availability.index'
import { Route as SourcesSourceIdRouteImport } from './routes/sources.$sourceId'
import { Route as GuidanceGuidanceIdRouteImport } from './routes/guidance.$guidanceId'
import { Route as GuardrailsGuardrailIdRouteImport } from './routes/guardrails.$guardrailId'
import { Route as CatalogTopicIdRouteImport } from './routes/catalog.$topicId'

const WhatsnewRoute = WhatsnewRouteImport.update({
  id: '/whatsnew',
  path: '/whatsnew',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidanceRoute = GuidanceRouteImport.update({
  id: '/guidance',
  path: '/guidance',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AvailabilityRoute = AvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesIndexRoute = SourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SourcesRoute,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidanceIndexRoute = GuidanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuidanceRoute,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CatalogRoute,
} as any)
const AvailabilityIndexRoute = AvailabilityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AvailabilityRoute,
} as any)
const SourcesSourceIdRoute = SourcesSourceIdRouteImport.update({
  id: '/$sourceId',
  path: '/$sourceId',
  getParentRoute: () => SourcesRoute,
} as any)
const GuidanceGuidanceIdRoute = GuidanceGuidanceIdRouteImport.update({
  id: '/$guidanceId',
  path: '/$guidanceId',
  getParentRoute: () => GuidanceRoute,
} as any)
const GuardrailsGuardrailIdRoute = GuardrailsGuardrailIdRouteImport.update({
  id: '/guardrails/$guardrailId',
  path: '/guardrails/$guardrailId',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogTopicIdRoute = CatalogTopicIdRouteImport.update({
  id: '/$topicId',
  path: '/$topicId',
  getParentRoute: () => CatalogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/availability': typeof AvailabilityRouteWithChildren
  '/catalog': typeof CatalogRouteWithChildren
  '/guidance': typeof GuidanceRouteWithChildren
  '/overview': typeof OverviewRoute
  '/sources': typeof SourcesRouteWithChildren
  '/whatsnew': typeof WhatsnewRoute
  '/catalog/$topicId': typeof CatalogTopicIdRoute
  '/guardrails/$guardrailId': typeof GuardrailsGuardrailIdRoute
  '/guidance/$guidanceId': typeof GuidanceGuidanceIdRoute
  '/sources/$sourceId': typeof SourcesSourceIdRoute
  '/availability/': typeof AvailabilityIndexRoute
  '/catalog/': typeof CatalogIndexRoute
  '/guidance/': typeof GuidanceIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/sources/': typeof SourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/overview': typeof OverviewRoute
  '/whatsnew': typeof WhatsnewRoute
  '/catalog/$topicId': typeof CatalogTopicIdRoute
  '/guardrails/$guardrailId': typeof GuardrailsGuardrailIdRoute
  '/guidance/$guidanceId': typeof GuidanceGuidanceIdRoute
  '/sources/$sourceId': typeof SourcesSourceIdRoute
  '/availability': typeof AvailabilityIndexRoute
  '/catalog': typeof CatalogIndexRoute
  '/guidance': typeof GuidanceIndexRoute
  '/skills': typeof SkillsIndexRoute
  '/sources': typeof SourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/availability': typeof AvailabilityRouteWithChildren
  '/catalog': typeof CatalogRouteWithChildren
  '/guidance': typeof GuidanceRouteWithChildren
  '/overview': typeof OverviewRoute
  '/sources': typeof SourcesRouteWithChildren
  '/whatsnew': typeof WhatsnewRoute
  '/catalog/$topicId': typeof CatalogTopicIdRoute
  '/guardrails/$guardrailId': typeof GuardrailsGuardrailIdRoute
  '/guidance/$guidanceId': typeof GuidanceGuidanceIdRoute
  '/sources/$sourceId': typeof SourcesSourceIdRoute
  '/availability/': typeof AvailabilityIndexRoute
  '/catalog/': typeof CatalogIndexRoute
  '/guidance/': typeof GuidanceIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/sources/': typeof SourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask'
    | '/availability'
    | '/catalog'
    | '/guidance'
    | '/overview'
    | '/sources'
    | '/whatsnew'
    | '/catalog/$topicId'
    | '/guardrails/$guardrailId'
    | '/guidance/$guidanceId'
    | '/sources/$sourceId'
    | '/availability/'
    | '/catalog/'
    | '/guidance/'
    | '/skills/'
    | '/sources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/overview'
    | '/whatsnew'
    | '/catalog/$topicId'
    | '/guardrails/$guardrailId'
    | '/guidance/$guidanceId'
    | '/sources/$sourceId'
    | '/availability'
    | '/catalog'
    | '/guidance'
    | '/skills'
    | '/sources'
  id:
    | '__root__'
    | '/'
    | '/ask'
    | '/availability'
    | '/catalog'
    | '/guidance'
    | '/overview'
    | '/sources'
    | '/whatsnew'
    | '/catalog/$topicId'
    | '/guardrails/$guardrailId'
    | '/guidance/$guidanceId'
    | '/sources/$sourceId'
    | '/availability/'
    | '/catalog/'
    | '/guidance/'
    | '/skills/'
    | '/sources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskRoute: typeof AskRoute
  AvailabilityRoute: typeof AvailabilityRouteWithChildren
  CatalogRoute: typeof CatalogRouteWithChildren
  GuidanceRoute: typeof GuidanceRouteWithChildren
  OverviewRoute: typeof OverviewRoute
  SourcesRoute: typeof SourcesRouteWithChildren
  WhatsnewRoute: typeof WhatsnewRoute
  GuardrailsGuardrailIdRoute: typeof GuardrailsGuardrailIdRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatsnew': {
      id: '/whatsnew'
      path: '/whatsnew'
      fullPath: '/whatsnew'
      preLoaderRoute: typeof WhatsnewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidance': {
      id: '/guidance'
      path: '/guidance'
      fullPath: '/guidance'
      preLoaderRoute: typeof GuidanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/availability': {
      id: '/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/': {
      id: '/sources/'
      path: '/'
      fullPath: '/sources/'
      preLoaderRoute: typeof SourcesIndexRouteImport
      parentRoute: typeof SourcesRoute
    }
    '/skills/': {
      id: '/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidance/': {
      id: '/guidance/'
      path: '/'
      fullPath: '/guidance/'
      preLoaderRoute: typeof GuidanceIndexRouteImport
      parentRoute: typeof GuidanceRoute
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/'
      fullPath: '/catalog/'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/availability/': {
      id: '/availability/'
      path: '/'
      fullPath: '/availability/'
      preLoaderRoute: typeof AvailabilityIndexRouteImport
      parentRoute: typeof AvailabilityRoute
    }
    '/sources/$sourceId': {
      id: '/sources/$sourceId'
      path: '/$sourceId'
      fullPath: '/sources/$sourceId'
      preLoaderRoute: typeof SourcesSourceIdRouteImport
      parentRoute: typeof SourcesRoute
    }
    '/guidance/$guidanceId': {
      id: '/guidance/$guidanceId'
      path: '/$guidanceId'
      fullPath: '/guidance/$guidanceId'
      preLoaderRoute: typeof GuidanceGuidanceIdRouteImport
      parentRoute: typeof GuidanceRoute
    }
    '/guardrails/$guardrailId': {
      id: '/guardrails/$guardrailId'
      path: '/guardrails/$guardrailId'
      fullPath: '/guardrails/$guardrailId'
      preLoaderRoute: typeof GuardrailsGuardrailIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/$topicId': {
      id: '/catalog/$topicId'
      path: '/$topicId'
      fullPath: '/catalog/$topicId'
      preLoaderRoute: typeof CatalogTopicIdRouteImport
      parentRoute: typeof CatalogRoute
    }
  }
}

interface AvailabilityRouteChildren {
  AvailabilityIndexRoute: typeof AvailabilityIndexRoute
}

const AvailabilityRouteChildren: AvailabilityRouteChildren = {
  AvailabilityIndexRoute: AvailabilityIndexRoute,
}

const AvailabilityRouteWithChildren = AvailabilityRoute._addFileChildren(
  AvailabilityRouteChildren,
)

interface CatalogRouteChildren {
  CatalogTopicIdRoute: typeof CatalogTopicIdRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
}

const CatalogRouteChildren: CatalogRouteChildren = {
  CatalogTopicIdRoute: CatalogTopicIdRoute,
  CatalogIndexRoute: CatalogIndexRoute,
}

const CatalogRouteWithChildren =
  CatalogRoute._addFileChildren(CatalogRouteChildren)

interface GuidanceRouteChildren {
  GuidanceGuidanceIdRoute: typeof GuidanceGuidanceIdRoute
  GuidanceIndexRoute: typeof GuidanceIndexRoute
}

const GuidanceRouteChildren: GuidanceRouteChildren = {
  GuidanceGuidanceIdRoute: GuidanceGuidanceIdRoute,
  GuidanceIndexRoute: GuidanceIndexRoute,
}

const GuidanceRouteWithChildren = GuidanceRoute._addFileChildren(
  GuidanceRouteChildren,
)

interface SourcesRouteChildren {
  SourcesSourceIdRoute: typeof SourcesSourceIdRoute
  SourcesIndexRoute: typeof SourcesIndexRoute
}

const SourcesRouteChildren: SourcesRouteChildren = {
  SourcesSourceIdRoute: SourcesSourceIdRoute,
  SourcesIndexRoute: SourcesIndexRoute,
}

const SourcesRouteWithChildren =
  SourcesRoute._addFileChildren(SourcesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskRoute: AskRoute,
  AvailabilityRoute: AvailabilityRouteWithChildren,
  CatalogRoute: CatalogRouteWithChildren,
  GuidanceRoute: GuidanceRouteWithChildren,
  OverviewRoute: OverviewRoute,
  SourcesRoute: SourcesRouteWithChildren,
  WhatsnewRoute: WhatsnewRoute,
  GuardrailsGuardrailIdRoute: GuardrailsGuardrailIdRoute,
  SkillsIndexRoute: SkillsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
